/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wufan_wfcrontabjob_service_jni_AntiCrackingCfgJni */

#ifndef _Included_com_wufan_wfcrontabjob_service_jni_AntiCrackingCfgJni
#define _Included_com_wufan_wfcrontabjob_service_jni_AntiCrackingCfgJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wufan_wfcrontabjob_service_jni_AntiCrackingCfgJni
 * Method:    convertContent
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wufan_wfcrontabjob_service_jni_AntiCrackingCfgJni_convertContent
  (JNIEnv *, jclass, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
