/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bkhech_home_practice_jni_JNITest */

#ifndef _Included_com_bkhech_home_practice_jni_JNITest
#define _Included_com_bkhech_home_practice_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bkhech_home_practice_jni_JNITest
 * Method:    callCppMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bkhech_home_practice_jni_JNITest_callCppMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
